[build]
  # 构建命令
  # Build command
  command = "npm run build"
  
  # 发布目录
  # Publish directory
  publish = "out"
  
  # Node.js版本
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

[build.processing]
  # 启用压缩
  # Enable compression
  skip_processing = false

[build.processing.css]
  # CSS压缩
  # CSS compression
  bundle = true
  minify = true

[build.processing.js]
  # JavaScript压缩
  # JavaScript compression
  bundle = true
  minify = true

[build.processing.html]
  # HTML压缩
  # HTML compression
  pretty_urls = true

# 重定向规则
# Redirect rules
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# 安全头
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态资源缓存
# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 环境变量
# Environment variables
[context.production.environment]
  NEXT_PUBLIC_APP_NAME = "AI Community MVP v2"
  NEXT_PUBLIC_APP_VERSION = "1.0.0"
  NEXT_PUBLIC_APP_URL = "https://your-site.netlify.app"
